version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: terraform
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      terraform-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/app"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/app"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      docker-base-image:
        patterns:
          - "*"
